// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecVW_SfM4TH6wz6sTdYpEnTy2n8ZpjOE',
    appId: '1:323555468101:android:b5ce6cbe7f169b7ffa942c',
    messagingSenderId: '323555468101',
    projectId: 'praxis-auth-db',
    databaseURL: 'https://praxis-auth-db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praxis-auth-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaNlFVZ4171AorsE8UcOSSBUvq9Xv3QaY',
    appId: '1:323555468101:ios:53d0614bb5aadf5dfa942c',
    messagingSenderId: '323555468101',
    projectId: 'praxis-auth-db',
    databaseURL: 'https://praxis-auth-db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praxis-auth-db.firebasestorage.app',
    iosBundleId: 'com.example.praxis',
  );
}
